[package]
name = "pica-lsp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bumpalo = { version = "3.13.0", features = ["collections"] }
codespan = { version = "0.11.1", features = ["serde", "serialization"] }
nom = "7.1.3"
nom_locate = "4.2.0"
serde = { version = "1.0.195", features = ["derive"] }
typesum = "0.2.0"
