[package]
name = "pican_check"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.14", features = ["derive"] }
codespan-reporting = "0.11.1"
serde_json = "1.0.111"
