//! This file is automatically generated as part of the build, do not edit it by hand
use pican_core::context::{IrContext, PicanContext};
use pican_ty::*;

include!(concat!(env!("OUT_DIR"), "/all_programs_compile.rs"));
