//! This file is automatically generated as part of the build, do not edit it by hand
use pican::context::{IrContext, PicanContext};
use pican::ty::*;

include!(concat!(env!("OUT_DIR"), "/all_programs_compile.rs"));
